### ISSUE TITLE
Home Page for MVC Frontend

### ISSUE THREAD

**Issue by AndoJoshuaBSIT32E1** [BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1_Student_Assessments#4]
### Get the project at the resporitory in github and create the Home page design  given the following design from figma:

**Acceptance criteria:**

- must have commits to github and each commit should create a new branch
- the design must be same to UI design provided below
- dont forget to commit it,  your grades will depends on your every commit

**Requirements**:

1. Should displat the TVL & Academic Strands
2. Must have footer
3. The design from figma must apply in Frontend

 
**Tool**

Link from Figma: [Home Page](https://github.com/BSIT32E1-STUDENT-ASSESSMENT/ELEC2024_GROUP2_BSIT32E1/issues/5)

**Comment by CoderDeepakJoura** [comment]
what are your requirements ?
